# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muruca_widgets}
  s.version = "0.2.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Hahn"]
  s.date = %q{2010-11-22}
  s.description = %q{Some additional interface elements to be used on Muruca sites.}
  s.email = %q{ghub@limitedcreativity.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "generators/colorbox/colorbox_generator.rb",
     "generators/colorbox/templates/README",
     "generators/colorbox/templates/_colorbox.html.erb",
     "generators/colorbox/templates/colorbox/colorbox.css",
     "generators/colorbox/templates/colorbox/images/border.png",
     "generators/colorbox/templates/colorbox/images/controls.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderBottomCenter.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderBottomLeft.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderBottomRight.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderMiddleLeft.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderMiddleRight.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderTopCenter.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderTopLeft.png",
     "generators/colorbox/templates/colorbox/images/internet_explorer/borderTopRight.png",
     "generators/colorbox/templates/colorbox/images/loading.gif",
     "generators/colorbox/templates/colorbox/images/loading_background.png",
     "generators/colorbox/templates/colorbox/images/overlay.png",
     "generators/colorbox/templates/jquery-1.3.2.min.js",
     "generators/colorbox/templates/jquery.colorbox.js",
     "generators/flexiip_viewer/flexiip_viewer_generator.rb",
     "generators/flexiip_viewer/templates/README",
     "generators/flexiip_viewer/templates/_flexiip_viewer.html.erb",
     "generators/flexiip_viewer/templates/config.default.xml",
     "generators/flexiip_viewer/templates/flexiip.swf",
     "generators/flexiip_viewer/templates/flexiip_helper.rb",
     "generators/generator_helpers.rb",
     "generators/google_map/google_map_generator.rb",
     "generators/google_map/templates/README",
     "generators/google_map/templates/_google_map.html.erb",
     "generators/google_map/templates/google_map.js",
     "generators/google_map/templates/google_map_helper.rb",
     "generators/google_map/templates/jquery-1.3.2.min.js",
     "generators/iip_viewer/iip_viewer_generator.rb",
     "generators/iip_viewer/templates/README",
     "generators/iip_viewer/templates/_iip_flash_viewer.html.erb",
     "generators/iip_viewer/templates/fliipish.swf",
     "generators/iip_viewer/templates/iip_flashclient.js",
     "generators/iip_viewer/templates/iip_helper.rb",
     "generators/iip_viewer/templates/swfobject.js",
     "generators/ipod_dropdown/ipod_dropdown_generator.rb",
     "generators/ipod_dropdown/templates/README",
     "generators/ipod_dropdown/templates/_ipod_dropdown.html.erb",
     "generators/ipod_dropdown/templates/fg.menu.js",
     "generators/ipod_dropdown/templates/fg.menu.js.orig",
     "generators/ipod_dropdown/templates/ipod-menu/fg.menu.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_flat_0_aaaaaa_40x100.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_flat_55_fbec88_40x100.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_glass_75_d0e5f5_1x400.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_glass_85_dfeffc_1x400.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_glass_95_fef1ec_1x400.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_inset-hard_100_f5f8f9_1x100.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-bg_inset-hard_100_fcfdfd_1x100.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_217bc0_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_2e83ff_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_469bdd_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_6da8d5_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_cd0a0a_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_d8e7f3_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/images/ui-icons_f9bd01_256x240.png",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.accordion.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.all.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.base.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.core.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.datepicker.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.dialog.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.progressbar.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.resizable.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.slider.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.tabs.css",
     "generators/ipod_dropdown/templates/ipod-menu/theme/ui.theme.css",
     "generators/ipod_dropdown/templates/ipod_dropdown_helper.rb",
     "generators/ipod_dropdown/templates/ipod_menu.js",
     "generators/ipod_dropdown/templates/jquery-1.3.2.min.js",
     "generators/ipod_dropdown/templates/patch.diff",
     "generators/simile_timeline/simile_timeline_generator.rb",
     "generators/simile_timeline/templates/README",
     "generators/simile_timeline/templates/_timeline.html.erb",
     "generators/simile_timeline/templates/_timeline_include.html.erb",
     "generators/simile_timeline/templates/jquery-1.3.2.min.js",
     "generators/simile_timeline/templates/timeline.js",
     "generators/simile_timeline/templates/timeline_ajax/content/history.html",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-arrow-point-down.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-arrow-point-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-arrow-point-right.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-arrow-point-up.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-bottom-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-bottom-right.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-bottom.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-right.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-top-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-top-right.png",
     "generators/simile_timeline/templates/timeline_ajax/images/bubble-top.png",
     "generators/simile_timeline/templates/timeline_ajax/images/close-button.png",
     "generators/simile_timeline/templates/timeline_ajax/images/copy.png",
     "generators/simile_timeline/templates/timeline_ajax/images/message-bottom-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/message-bottom-right.png",
     "generators/simile_timeline/templates/timeline_ajax/images/message-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/message-right.png",
     "generators/simile_timeline/templates/timeline_ajax/images/message-top-left.png",
     "generators/simile_timeline/templates/timeline_ajax/images/message-top-right.png",
     "generators/simile_timeline/templates/timeline_ajax/scripts/signal.js",
     "generators/simile_timeline/templates/timeline_ajax/simile-ajax-api.js",
     "generators/simile_timeline/templates/timeline_ajax/simile-ajax-bundle.js",
     "generators/simile_timeline/templates/timeline_ajax/styles/graphics-ie6.css",
     "generators/simile_timeline/templates/timeline_ajax/styles/graphics.css",
     "generators/simile_timeline/templates/timeline_helper.rb",
     "generators/simile_timeline/templates/timeline_js/images/blue-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-bottom-arrow.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-bottom-left.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-bottom-right.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-bottom.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-left-arrow.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-left.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-right-arrow.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-right.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-top-arrow.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-top-left.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-top-right.png",
     "generators/simile_timeline/templates/timeline_js/images/bubble-top.png",
     "generators/simile_timeline/templates/timeline_js/images/close-button.png",
     "generators/simile_timeline/templates/timeline_js/images/copyright-vertical.png",
     "generators/simile_timeline/templates/timeline_js/images/copyright.png",
     "generators/simile_timeline/templates/timeline_js/images/dark-blue-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/dark-green-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/dark-red-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/dull-blue-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/dull-green-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/dull-red-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/gray-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/green-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/message-bottom-left.png",
     "generators/simile_timeline/templates/timeline_js/images/message-bottom-right.png",
     "generators/simile_timeline/templates/timeline_js/images/message-left.png",
     "generators/simile_timeline/templates/timeline_js/images/message-right.png",
     "generators/simile_timeline/templates/timeline_js/images/message-top-left.png",
     "generators/simile_timeline/templates/timeline_js/images/message-top-right.png",
     "generators/simile_timeline/templates/timeline_js/images/progress-running.gif",
     "generators/simile_timeline/templates/timeline_js/images/red-circle.png",
     "generators/simile_timeline/templates/timeline_js/images/top-bubble.png",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/cs/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/cs/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/de/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/de/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/en/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/en/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/es/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/es/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/fr/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/fr/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/it/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/it/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/nl/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/nl/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/ru/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/ru/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/se/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/se/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/tr/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/tr/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/vi/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/vi/timeline.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/zh/labellers.js",
     "generators/simile_timeline/templates/timeline_js/scripts/l10n/zh/timeline.js",
     "generators/simile_timeline/templates/timeline_js/timeline-api.js",
     "generators/simile_timeline/templates/timeline_js/timeline-bundle.css",
     "generators/simile_timeline/templates/timeline_js/timeline-bundle.js",
     "lib/muruca_widgets.rb",
     "lib/timeline.rb",
     "lib/timeline_source.rb"
  ]
  s.homepage = %q{http://net7.github.com/muruca_widgets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Additional interface elements for Muruca Sites.}
  s.test_files = [
    "test/muruca_widgets_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 1.1.0"])
    else
      s.add_dependency(%q<json>, [">= 1.1.0"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.1.0"])
  end
end

